apiVersion: v1
kind: Service
metadata:
  labels:
    app: drone-analysis
  name: drone-analysis
spec:
  selector:
    app: drone-analysis
  ports:
  - name: http
    port: 7788
    protocol: TCP
    targetPort: 9999
